version: "3.9"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  cron-webhook:
    image: ghcr.io/sebasptsch/cron-webhook:latest
    environment:
      - DATABASE_URL=/data/cron-webhook.db
      - CRON_TZ=Australia/Sydney
    volumes:
      - webhook-data:/data
    ports:
      - 3000:3000
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: frontend-runner
  #   ports:
  #     - 3000:3000
  #   env_file: packages/frontend/.env.local
  #   links:
  #     - postgres

volumes:
  postgres-data:
  webhook-data:
