version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  kronos:
    image: ghcr.io/ostafen/kronos
    network_mode: host
    environment:
      - PORT=9175 # configuration properties can be overridden through environment variables
      - STORE_PATH=/data/kronos.bolt
      - CRON_TZ=Australia/Sydney
      - TZ=Australia/Sydney
    volumes:
      - kronos-data:/data
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: frontend-runner
  #   ports:
  #     - 3000:3000
  #   env_file: packages/frontend/.env.local
  #   links:
  #     - postgres

volumes:
  postgres-data:
  kronos-data:
