version: "3.9"

services:
  postgres:
    restart: unless-stopped
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  cron-webhook:
    restart: unless-stopped
    image: ghcr.io/sebasptsch/cron-webhook:latest
    environment:
      - DATABASE_URL=/data/cron-webhook.db
      - CRON_TZ=Australia/Sydney
    volumes:
      - webhook-data:/data
  attendance-system:
    restart: unless-stopped
    image: ghcr.io/team3132/attendancesystem-frontend:latest
    ports:
      - 1420:1420
    env_file: ./.env
    links:
      - postgres
      - cron-webhook

volumes:
  postgres-data:
  webhook-data:
