FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV production
ARG VERSION
ENV VERSION=$VERSION
COPY package.json yarn.lock ./
COPY packages/backend/dist packages/backend/dist
COPY packages/backend/package.json ./packages/backend/
RUN apk add --no-cache build-base g++ python3 cairo-dev jpeg-dev pango-dev giflib-dev
RUN yarn back install --frozen-lockfile --production

EXPOSE 3000
CMD yarn back start