import { Inject, Injectable, UseGuards, UseInterceptors } from '@nestjs/common';
import { SlashCommand, Context, type SlashCommandContext } from 'necord';

import { EventAutocompleteInterceptor } from '../interceptors/event.interceptor';
import { DateTime, Duration } from 'luxon';
import { LeaderBoardUser } from 'backend/schema';
import { z } from 'zod';
import { BACKEND_TOKEN, type BackendClient } from '@/backend/backend.module';
import { GuildMemberGuard } from '../guards/GuildMemberGuard';

const leaderboardLine = (data: z.infer<typeof LeaderBoardUser>) =>
  `${data.rank}. **${data.username}** - ${Duration.fromISO(
    data.duration,
  ).toHuman()}`;

const guildId = process.env['GUILD_ID'];

function splitMessage(message: string): string[] {
  const maxChars = 2000;
  const chunks: string[] = [];

  while (message.length > 0) {
    // Find the next newline character or the end of the message
    const newlineIndex = message.indexOf('\n');
    const endIndex = newlineIndex !== -1 ? newlineIndex : message.length;

    // Extract the chunk up to the newline or end of the message
    const chunk = message.substring(0, endIndex);

    // If the chunk is within the character limit, add it to the array
    if (chunk.length <= maxChars) {
      chunks.push(chunk);
      // Remove the processed part from the message
      message = message.substring(endIndex + 1);
    } else {
      // If the chunk exceeds the character limit, split it
      chunks.push(chunk.substring(0, maxChars));
      // Remove the processed part from the message
      message = chunk.substring(maxChars);
    }
  }

  return chunks;
}

@Injectable()
export class LeaderBoardCommand {
  constructor(
    @Inject(BACKEND_TOKEN) private readonly backendClient: BackendClient,
  ) {}

  @UseGuards(GuildMemberGuard)
  @UseInterceptors(EventAutocompleteInterceptor)
  @SlashCommand({
    name: 'leaderboard',
    description: 'Get the leaderboard for outreach hours',
    guilds: guildId ? [guildId] : undefined,
    dmPermission: false,
  })
  public async onLeaderboard(@Context() [interaction]: SlashCommandContext) {
    const currentLeaderboard =
      await this.backendClient.client.bot.leaderboard.query();

    const headerLine = `# Outreach Leaderboard`;

    const contentLines = currentLeaderboard.map(leaderboardLine).join('\n');

    const footerLine = `### Generated by ${interaction.user.toString()} at ${DateTime.local().toLocaleString(
      DateTime.DATETIME_MED,
    )}`;

    const joined = [headerLine, contentLines, footerLine].join('\n');

    const split = splitMessage(joined);

    if (split.length > 1) {
      await interaction.reply(split[0]);
      for (const message of split.slice(1)) {
        await interaction.followUp(message);
      }
    }
  }
}
