/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin_'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin_/index'
import { Route as AuthenticatedProfileSessionsRouteImport } from './routes/_authenticated/profile/sessions'
import { Route as AuthenticatedProfilePendingRouteImport } from './routes/_authenticated/profile/pending'
import { Route as AuthenticatedEventsCreateRouteImport } from './routes/_authenticated/events/create'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events/$eventId'
import { Route as AuthenticatedEventsEventIdIndexRouteImport } from './routes/_authenticated/events/$eventId/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin_/users/index'
import { Route as AuthenticatedAdminEventParsingIndexRouteImport } from './routes/_authenticated/admin_/event-parsing/index'
import { Route as AuthenticatedAdminApiKeysIndexRouteImport } from './routes/_authenticated/admin_/api-keys/index'
import { Route as AuthenticatedEventsEventIdQrCodeRouteImport } from './routes/_authenticated/events/$eventId/qr-code'
import { Route as AuthenticatedEventsEventIdCheckInRouteImport } from './routes/_authenticated/events/$eventId/check-in'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin_/users/$userId'
import { Route as AuthenticatedAdminEventParsingCreateRouteImport } from './routes/_authenticated/admin_/event-parsing/create'
import { Route as AuthenticatedAdminEventParsingRuleIdRouteImport } from './routes/_authenticated/admin_/event-parsing/$ruleId'
import { Route as AuthenticatedAdminApiKeysCreateRouteImport } from './routes/_authenticated/admin_/api-keys/create'
import { Route as AuthenticatedAdminUsersUserIdIndexRouteImport } from './routes/_authenticated/admin_/users/$userId/index'
import { Route as AuthenticatedAdminUsersUserIdSummaryRouteImport } from './routes/_authenticated/admin_/users/$userId/summary'
import { Route as AuthenticatedAdminUsersUserIdSessionsRouteImport } from './routes/_authenticated/admin_/users/$userId/sessions'
import { Route as AuthenticatedAdminUsersUserIdPendingRouteImport } from './routes/_authenticated/admin_/users/$userId/pending'

// Create/Update Routes

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin_',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedProfileSessionsRoute =
  AuthenticatedProfileSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

const AuthenticatedProfilePendingRoute =
  AuthenticatedProfilePendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

const AuthenticatedEventsCreateRoute =
  AuthenticatedEventsCreateRouteImport.update({
    id: '/events/create',
    path: '/events/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedEventsEventIdIndexRoute =
  AuthenticatedEventsEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)

const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

const AuthenticatedAdminEventParsingIndexRoute =
  AuthenticatedAdminEventParsingIndexRouteImport.update({
    id: '/event-parsing/',
    path: '/event-parsing/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

const AuthenticatedAdminApiKeysIndexRoute =
  AuthenticatedAdminApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

const AuthenticatedEventsEventIdQrCodeRoute =
  AuthenticatedEventsEventIdQrCodeRouteImport.update({
    id: '/qr-code',
    path: '/qr-code',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)

const AuthenticatedEventsEventIdCheckInRoute =
  AuthenticatedEventsEventIdCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)

const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

const AuthenticatedAdminEventParsingCreateRoute =
  AuthenticatedAdminEventParsingCreateRouteImport.update({
    id: '/event-parsing/create',
    path: '/event-parsing/create',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

const AuthenticatedAdminEventParsingRuleIdRoute =
  AuthenticatedAdminEventParsingRuleIdRouteImport.update({
    id: '/event-parsing/$ruleId',
    path: '/event-parsing/$ruleId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

const AuthenticatedAdminApiKeysCreateRoute =
  AuthenticatedAdminApiKeysCreateRouteImport.update({
    id: '/api-keys/create',
    path: '/api-keys/create',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

const AuthenticatedAdminUsersUserIdIndexRoute =
  AuthenticatedAdminUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)

const AuthenticatedAdminUsersUserIdSummaryRoute =
  AuthenticatedAdminUsersUserIdSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)

const AuthenticatedAdminUsersUserIdSessionsRoute =
  AuthenticatedAdminUsersUserIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)

const AuthenticatedAdminUsersUserIdPendingRoute =
  AuthenticatedAdminUsersUserIdPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin_': {
      id: '/_authenticated/admin_'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/events/create': {
      id: '/_authenticated/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof AuthenticatedEventsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/profile/pending': {
      id: '/_authenticated/profile/pending'
      path: '/pending'
      fullPath: '/profile/pending'
      preLoaderRoute: typeof AuthenticatedProfilePendingRouteImport
      parentRoute: typeof AuthenticatedProfileRouteImport
    }
    '/_authenticated/profile/sessions': {
      id: '/_authenticated/profile/sessions'
      path: '/sessions'
      fullPath: '/profile/sessions'
      preLoaderRoute: typeof AuthenticatedProfileSessionsRouteImport
      parentRoute: typeof AuthenticatedProfileRouteImport
    }
    '/_authenticated/admin_/': {
      id: '/_authenticated/admin_/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRouteImport
    }
    '/_authenticated/admin_/api-keys/create': {
      id: '/_authenticated/admin_/api-keys/create'
      path: '/api-keys/create'
      fullPath: '/admin/api-keys/create'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysCreateRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin_/event-parsing/$ruleId': {
      id: '/_authenticated/admin_/event-parsing/$ruleId'
      path: '/event-parsing/$ruleId'
      fullPath: '/admin/event-parsing/$ruleId'
      preLoaderRoute: typeof AuthenticatedAdminEventParsingRuleIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin_/event-parsing/create': {
      id: '/_authenticated/admin_/event-parsing/create'
      path: '/event-parsing/create'
      fullPath: '/admin/event-parsing/create'
      preLoaderRoute: typeof AuthenticatedAdminEventParsingCreateRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin_/users/$userId': {
      id: '/_authenticated/admin_/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/events/$eventId/check-in': {
      id: '/_authenticated/events/$eventId/check-in'
      path: '/check-in'
      fullPath: '/events/$eventId/check-in'
      preLoaderRoute: typeof AuthenticatedEventsEventIdCheckInRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteImport
    }
    '/_authenticated/events/$eventId/qr-code': {
      id: '/_authenticated/events/$eventId/qr-code'
      path: '/qr-code'
      fullPath: '/events/$eventId/qr-code'
      preLoaderRoute: typeof AuthenticatedEventsEventIdQrCodeRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteImport
    }
    '/_authenticated/admin_/api-keys/': {
      id: '/_authenticated/admin_/api-keys/'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin_/event-parsing/': {
      id: '/_authenticated/admin_/event-parsing/'
      path: '/event-parsing'
      fullPath: '/admin/event-parsing'
      preLoaderRoute: typeof AuthenticatedAdminEventParsingIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/admin_/users/': {
      id: '/_authenticated/admin_/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteImport
    }
    '/_authenticated/events/$eventId/': {
      id: '/_authenticated/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteImport
    }
    '/_authenticated/admin_/users/$userId/pending': {
      id: '/_authenticated/admin_/users/$userId/pending'
      path: '/pending'
      fullPath: '/admin/users/$userId/pending'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdPendingRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
    }
    '/_authenticated/admin_/users/$userId/sessions': {
      id: '/_authenticated/admin_/users/$userId/sessions'
      path: '/sessions'
      fullPath: '/admin/users/$userId/sessions'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
    }
    '/_authenticated/admin_/users/$userId/summary': {
      id: '/_authenticated/admin_/users/$userId/summary'
      path: '/summary'
      fullPath: '/admin/users/$userId/summary'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdSummaryRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
    }
    '/_authenticated/admin_/users/$userId/': {
      id: '/_authenticated/admin_/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './routes/_authenticated' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated',
    FileRoutesByPath['/_authenticated']['parentRoute'],
    FileRoutesByPath['/_authenticated']['id'],
    FileRoutesByPath['/_authenticated']['path'],
    FileRoutesByPath['/_authenticated']['fullPath']
  >
}
declare module './routes/error' {
  const createFileRoute: CreateFileRoute<
    '/error',
    FileRoutesByPath['/error']['parentRoute'],
    FileRoutesByPath['/error']['id'],
    FileRoutesByPath['/error']['path'],
    FileRoutesByPath['/error']['fullPath']
  >
}
declare module './routes/login' {
  const createFileRoute: CreateFileRoute<
    '/login',
    FileRoutesByPath['/login']['parentRoute'],
    FileRoutesByPath['/login']['id'],
    FileRoutesByPath['/login']['path'],
    FileRoutesByPath['/login']['fullPath']
  >
}
declare module './routes/_authenticated/admin_' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_',
    FileRoutesByPath['/_authenticated/admin_']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_']['id'],
    FileRoutesByPath['/_authenticated/admin_']['path'],
    FileRoutesByPath['/_authenticated/admin_']['fullPath']
  >
}
declare module './routes/_authenticated/leaderboard' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/leaderboard',
    FileRoutesByPath['/_authenticated/leaderboard']['parentRoute'],
    FileRoutesByPath['/_authenticated/leaderboard']['id'],
    FileRoutesByPath['/_authenticated/leaderboard']['path'],
    FileRoutesByPath['/_authenticated/leaderboard']['fullPath']
  >
}
declare module './routes/_authenticated/profile' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/profile',
    FileRoutesByPath['/_authenticated/profile']['parentRoute'],
    FileRoutesByPath['/_authenticated/profile']['id'],
    FileRoutesByPath['/_authenticated/profile']['path'],
    FileRoutesByPath['/_authenticated/profile']['fullPath']
  >
}
declare module './routes/_authenticated/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/',
    FileRoutesByPath['/_authenticated/']['parentRoute'],
    FileRoutesByPath['/_authenticated/']['id'],
    FileRoutesByPath['/_authenticated/']['path'],
    FileRoutesByPath['/_authenticated/']['fullPath']
  >
}
declare module './routes/_authenticated/events/$eventId' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/events/$eventId',
    FileRoutesByPath['/_authenticated/events/$eventId']['parentRoute'],
    FileRoutesByPath['/_authenticated/events/$eventId']['id'],
    FileRoutesByPath['/_authenticated/events/$eventId']['path'],
    FileRoutesByPath['/_authenticated/events/$eventId']['fullPath']
  >
}
declare module './routes/_authenticated/events/create' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/events/create',
    FileRoutesByPath['/_authenticated/events/create']['parentRoute'],
    FileRoutesByPath['/_authenticated/events/create']['id'],
    FileRoutesByPath['/_authenticated/events/create']['path'],
    FileRoutesByPath['/_authenticated/events/create']['fullPath']
  >
}
declare module './routes/_authenticated/profile/pending' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/profile/pending',
    FileRoutesByPath['/_authenticated/profile/pending']['parentRoute'],
    FileRoutesByPath['/_authenticated/profile/pending']['id'],
    FileRoutesByPath['/_authenticated/profile/pending']['path'],
    FileRoutesByPath['/_authenticated/profile/pending']['fullPath']
  >
}
declare module './routes/_authenticated/profile/sessions' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/profile/sessions',
    FileRoutesByPath['/_authenticated/profile/sessions']['parentRoute'],
    FileRoutesByPath['/_authenticated/profile/sessions']['id'],
    FileRoutesByPath['/_authenticated/profile/sessions']['path'],
    FileRoutesByPath['/_authenticated/profile/sessions']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/',
    FileRoutesByPath['/_authenticated/admin_/']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/']['id'],
    FileRoutesByPath['/_authenticated/admin_/']['path'],
    FileRoutesByPath['/_authenticated/admin_/']['fullPath']
  >
}
declare module './routes/_authenticated/events/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/events/',
    FileRoutesByPath['/_authenticated/events/']['parentRoute'],
    FileRoutesByPath['/_authenticated/events/']['id'],
    FileRoutesByPath['/_authenticated/events/']['path'],
    FileRoutesByPath['/_authenticated/events/']['fullPath']
  >
}
declare module './routes/_authenticated/profile/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/profile/',
    FileRoutesByPath['/_authenticated/profile/']['parentRoute'],
    FileRoutesByPath['/_authenticated/profile/']['id'],
    FileRoutesByPath['/_authenticated/profile/']['path'],
    FileRoutesByPath['/_authenticated/profile/']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/api-keys/create' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/api-keys/create',
    FileRoutesByPath['/_authenticated/admin_/api-keys/create']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/api-keys/create']['id'],
    FileRoutesByPath['/_authenticated/admin_/api-keys/create']['path'],
    FileRoutesByPath['/_authenticated/admin_/api-keys/create']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/event-parsing/$ruleId' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/event-parsing/$ruleId',
    FileRoutesByPath['/_authenticated/admin_/event-parsing/$ruleId']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/event-parsing/$ruleId']['id'],
    FileRoutesByPath['/_authenticated/admin_/event-parsing/$ruleId']['path'],
    FileRoutesByPath['/_authenticated/admin_/event-parsing/$ruleId']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/event-parsing/create' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/event-parsing/create',
    FileRoutesByPath['/_authenticated/admin_/event-parsing/create']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/event-parsing/create']['id'],
    FileRoutesByPath['/_authenticated/admin_/event-parsing/create']['path'],
    FileRoutesByPath['/_authenticated/admin_/event-parsing/create']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/users/$userId' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/users/$userId',
    FileRoutesByPath['/_authenticated/admin_/users/$userId']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId']['id'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId']['path'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId']['fullPath']
  >
}
declare module './routes/_authenticated/events/$eventId/check-in' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/events/$eventId/check-in',
    FileRoutesByPath['/_authenticated/events/$eventId/check-in']['parentRoute'],
    FileRoutesByPath['/_authenticated/events/$eventId/check-in']['id'],
    FileRoutesByPath['/_authenticated/events/$eventId/check-in']['path'],
    FileRoutesByPath['/_authenticated/events/$eventId/check-in']['fullPath']
  >
}
declare module './routes/_authenticated/events/$eventId/qr-code' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/events/$eventId/qr-code',
    FileRoutesByPath['/_authenticated/events/$eventId/qr-code']['parentRoute'],
    FileRoutesByPath['/_authenticated/events/$eventId/qr-code']['id'],
    FileRoutesByPath['/_authenticated/events/$eventId/qr-code']['path'],
    FileRoutesByPath['/_authenticated/events/$eventId/qr-code']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/api-keys/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/api-keys/',
    FileRoutesByPath['/_authenticated/admin_/api-keys/']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/api-keys/']['id'],
    FileRoutesByPath['/_authenticated/admin_/api-keys/']['path'],
    FileRoutesByPath['/_authenticated/admin_/api-keys/']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/event-parsing/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/event-parsing/',
    FileRoutesByPath['/_authenticated/admin_/event-parsing/']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/event-parsing/']['id'],
    FileRoutesByPath['/_authenticated/admin_/event-parsing/']['path'],
    FileRoutesByPath['/_authenticated/admin_/event-parsing/']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/users/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/users/',
    FileRoutesByPath['/_authenticated/admin_/users/']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/users/']['id'],
    FileRoutesByPath['/_authenticated/admin_/users/']['path'],
    FileRoutesByPath['/_authenticated/admin_/users/']['fullPath']
  >
}
declare module './routes/_authenticated/events/$eventId/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/events/$eventId/',
    FileRoutesByPath['/_authenticated/events/$eventId/']['parentRoute'],
    FileRoutesByPath['/_authenticated/events/$eventId/']['id'],
    FileRoutesByPath['/_authenticated/events/$eventId/']['path'],
    FileRoutesByPath['/_authenticated/events/$eventId/']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/users/$userId/pending' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/users/$userId/pending',
    FileRoutesByPath['/_authenticated/admin_/users/$userId/pending']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/pending']['id'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/pending']['path'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/pending']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/users/$userId/sessions' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/users/$userId/sessions',
    FileRoutesByPath['/_authenticated/admin_/users/$userId/sessions']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/sessions']['id'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/sessions']['path'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/sessions']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/users/$userId/summary' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/users/$userId/summary',
    FileRoutesByPath['/_authenticated/admin_/users/$userId/summary']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/summary']['id'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/summary']['path'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/summary']['fullPath']
  >
}
declare module './routes/_authenticated/admin_/users/$userId/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticated/admin_/users/$userId/',
    FileRoutesByPath['/_authenticated/admin_/users/$userId/']['parentRoute'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/']['id'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/']['path'],
    FileRoutesByPath['/_authenticated/admin_/users/$userId/']['fullPath']
  >
}

// Create and export the route tree

interface AuthenticatedAdminUsersUserIdRouteChildren {
  AuthenticatedAdminUsersUserIdPendingRoute: typeof AuthenticatedAdminUsersUserIdPendingRoute
  AuthenticatedAdminUsersUserIdSessionsRoute: typeof AuthenticatedAdminUsersUserIdSessionsRoute
  AuthenticatedAdminUsersUserIdSummaryRoute: typeof AuthenticatedAdminUsersUserIdSummaryRoute
  AuthenticatedAdminUsersUserIdIndexRoute: typeof AuthenticatedAdminUsersUserIdIndexRoute
}

const AuthenticatedAdminUsersUserIdRouteChildren: AuthenticatedAdminUsersUserIdRouteChildren =
  {
    AuthenticatedAdminUsersUserIdPendingRoute:
      AuthenticatedAdminUsersUserIdPendingRoute,
    AuthenticatedAdminUsersUserIdSessionsRoute:
      AuthenticatedAdminUsersUserIdSessionsRoute,
    AuthenticatedAdminUsersUserIdSummaryRoute:
      AuthenticatedAdminUsersUserIdSummaryRoute,
    AuthenticatedAdminUsersUserIdIndexRoute:
      AuthenticatedAdminUsersUserIdIndexRoute,
  }

const AuthenticatedAdminUsersUserIdRouteWithChildren =
  AuthenticatedAdminUsersUserIdRoute._addFileChildren(
    AuthenticatedAdminUsersUserIdRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminApiKeysCreateRoute: typeof AuthenticatedAdminApiKeysCreateRoute
  AuthenticatedAdminEventParsingRuleIdRoute: typeof AuthenticatedAdminEventParsingRuleIdRoute
  AuthenticatedAdminEventParsingCreateRoute: typeof AuthenticatedAdminEventParsingCreateRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  AuthenticatedAdminApiKeysIndexRoute: typeof AuthenticatedAdminApiKeysIndexRoute
  AuthenticatedAdminEventParsingIndexRoute: typeof AuthenticatedAdminEventParsingIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminApiKeysCreateRoute: AuthenticatedAdminApiKeysCreateRoute,
  AuthenticatedAdminEventParsingRuleIdRoute:
    AuthenticatedAdminEventParsingRuleIdRoute,
  AuthenticatedAdminEventParsingCreateRoute:
    AuthenticatedAdminEventParsingCreateRoute,
  AuthenticatedAdminUsersUserIdRoute:
    AuthenticatedAdminUsersUserIdRouteWithChildren,
  AuthenticatedAdminApiKeysIndexRoute: AuthenticatedAdminApiKeysIndexRoute,
  AuthenticatedAdminEventParsingIndexRoute:
    AuthenticatedAdminEventParsingIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfilePendingRoute: typeof AuthenticatedProfilePendingRoute
  AuthenticatedProfileSessionsRoute: typeof AuthenticatedProfileSessionsRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfilePendingRoute: AuthenticatedProfilePendingRoute,
  AuthenticatedProfileSessionsRoute: AuthenticatedProfileSessionsRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedEventsEventIdRouteChildren {
  AuthenticatedEventsEventIdCheckInRoute: typeof AuthenticatedEventsEventIdCheckInRoute
  AuthenticatedEventsEventIdQrCodeRoute: typeof AuthenticatedEventsEventIdQrCodeRoute
  AuthenticatedEventsEventIdIndexRoute: typeof AuthenticatedEventsEventIdIndexRoute
}

const AuthenticatedEventsEventIdRouteChildren: AuthenticatedEventsEventIdRouteChildren =
  {
    AuthenticatedEventsEventIdCheckInRoute:
      AuthenticatedEventsEventIdCheckInRoute,
    AuthenticatedEventsEventIdQrCodeRoute:
      AuthenticatedEventsEventIdQrCodeRoute,
    AuthenticatedEventsEventIdIndexRoute: AuthenticatedEventsEventIdIndexRoute,
  }

const AuthenticatedEventsEventIdRouteWithChildren =
  AuthenticatedEventsEventIdRoute._addFileChildren(
    AuthenticatedEventsEventIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRouteWithChildren
  AuthenticatedEventsCreateRoute: typeof AuthenticatedEventsCreateRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRouteWithChildren,
  AuthenticatedEventsCreateRoute: AuthenticatedEventsCreateRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRouteWithChildren
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/profile/sessions': typeof AuthenticatedProfileSessionsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/admin/api-keys/create': typeof AuthenticatedAdminApiKeysCreateRoute
  '/admin/event-parsing/$ruleId': typeof AuthenticatedAdminEventParsingRuleIdRoute
  '/admin/event-parsing/create': typeof AuthenticatedAdminEventParsingCreateRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  '/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysIndexRoute
  '/admin/event-parsing': typeof AuthenticatedAdminEventParsingIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
  '/admin/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/admin/users/$userId/sessions': typeof AuthenticatedAdminUsersUserIdSessionsRoute
  '/admin/users/$userId/summary': typeof AuthenticatedAdminUsersUserIdSummaryRoute
  '/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}

export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/profile/sessions': typeof AuthenticatedProfileSessionsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/admin/api-keys/create': typeof AuthenticatedAdminApiKeysCreateRoute
  '/admin/event-parsing/$ruleId': typeof AuthenticatedAdminEventParsingRuleIdRoute
  '/admin/event-parsing/create': typeof AuthenticatedAdminEventParsingCreateRoute
  '/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysIndexRoute
  '/admin/event-parsing': typeof AuthenticatedAdminEventParsingIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdIndexRoute
  '/admin/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/admin/users/$userId/sessions': typeof AuthenticatedAdminUsersUserIdSessionsRoute
  '/admin/users/$userId/summary': typeof AuthenticatedAdminUsersUserIdSummaryRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin_': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRouteWithChildren
  '/_authenticated/events/create': typeof AuthenticatedEventsCreateRoute
  '/_authenticated/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/_authenticated/profile/sessions': typeof AuthenticatedProfileSessionsRoute
  '/_authenticated/admin_/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/admin_/api-keys/create': typeof AuthenticatedAdminApiKeysCreateRoute
  '/_authenticated/admin_/event-parsing/$ruleId': typeof AuthenticatedAdminEventParsingRuleIdRoute
  '/_authenticated/admin_/event-parsing/create': typeof AuthenticatedAdminEventParsingCreateRoute
  '/_authenticated/admin_/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  '/_authenticated/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/_authenticated/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/_authenticated/admin_/api-keys/': typeof AuthenticatedAdminApiKeysIndexRoute
  '/_authenticated/admin_/event-parsing/': typeof AuthenticatedAdminEventParsingIndexRoute
  '/_authenticated/admin_/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
  '/_authenticated/admin_/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/_authenticated/admin_/users/$userId/sessions': typeof AuthenticatedAdminUsersUserIdSessionsRoute
  '/_authenticated/admin_/users/$userId/summary': typeof AuthenticatedAdminUsersUserIdSummaryRoute
  '/_authenticated/admin_/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/error'
    | '/login'
    | '/admin'
    | '/leaderboard'
    | '/profile'
    | '/'
    | '/events/$eventId'
    | '/events/create'
    | '/profile/pending'
    | '/profile/sessions'
    | '/admin/'
    | '/events'
    | '/profile/'
    | '/admin/api-keys/create'
    | '/admin/event-parsing/$ruleId'
    | '/admin/event-parsing/create'
    | '/admin/users/$userId'
    | '/events/$eventId/check-in'
    | '/events/$eventId/qr-code'
    | '/admin/api-keys'
    | '/admin/event-parsing'
    | '/admin/users'
    | '/events/$eventId/'
    | '/admin/users/$userId/pending'
    | '/admin/users/$userId/sessions'
    | '/admin/users/$userId/summary'
    | '/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/login'
    | '/leaderboard'
    | '/'
    | '/events/create'
    | '/profile/pending'
    | '/profile/sessions'
    | '/admin'
    | '/events'
    | '/profile'
    | '/admin/api-keys/create'
    | '/admin/event-parsing/$ruleId'
    | '/admin/event-parsing/create'
    | '/events/$eventId/check-in'
    | '/events/$eventId/qr-code'
    | '/admin/api-keys'
    | '/admin/event-parsing'
    | '/admin/users'
    | '/events/$eventId'
    | '/admin/users/$userId/pending'
    | '/admin/users/$userId/sessions'
    | '/admin/users/$userId/summary'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/error'
    | '/login'
    | '/_authenticated/admin_'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/events/create'
    | '/_authenticated/profile/pending'
    | '/_authenticated/profile/sessions'
    | '/_authenticated/admin_/'
    | '/_authenticated/events/'
    | '/_authenticated/profile/'
    | '/_authenticated/admin_/api-keys/create'
    | '/_authenticated/admin_/event-parsing/$ruleId'
    | '/_authenticated/admin_/event-parsing/create'
    | '/_authenticated/admin_/users/$userId'
    | '/_authenticated/events/$eventId/check-in'
    | '/_authenticated/events/$eventId/qr-code'
    | '/_authenticated/admin_/api-keys/'
    | '/_authenticated/admin_/event-parsing/'
    | '/_authenticated/admin_/users/'
    | '/_authenticated/events/$eventId/'
    | '/_authenticated/admin_/users/$userId/pending'
    | '/_authenticated/admin_/users/$userId/sessions'
    | '/_authenticated/admin_/users/$userId/summary'
    | '/_authenticated/admin_/users/$userId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/error",
        "/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/admin_",
        "/_authenticated/leaderboard",
        "/_authenticated/profile",
        "/_authenticated/",
        "/_authenticated/events/$eventId",
        "/_authenticated/events/create",
        "/_authenticated/events/"
      ]
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/admin_": {
      "filePath": "_authenticated/admin_.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin_/",
        "/_authenticated/admin_/api-keys/create",
        "/_authenticated/admin_/event-parsing/$ruleId",
        "/_authenticated/admin_/event-parsing/create",
        "/_authenticated/admin_/users/$userId",
        "/_authenticated/admin_/api-keys/",
        "/_authenticated/admin_/event-parsing/",
        "/_authenticated/admin_/users/"
      ]
    },
    "/_authenticated/leaderboard": {
      "filePath": "_authenticated/leaderboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/profile/pending",
        "/_authenticated/profile/sessions",
        "/_authenticated/profile/"
      ]
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/events/$eventId": {
      "filePath": "_authenticated/events/$eventId.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/events/$eventId/check-in",
        "/_authenticated/events/$eventId/qr-code",
        "/_authenticated/events/$eventId/"
      ]
    },
    "/_authenticated/events/create": {
      "filePath": "_authenticated/events/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile/pending": {
      "filePath": "_authenticated/profile/pending.tsx",
      "parent": "/_authenticated/profile"
    },
    "/_authenticated/profile/sessions": {
      "filePath": "_authenticated/profile/sessions.tsx",
      "parent": "/_authenticated/profile"
    },
    "/_authenticated/admin_/": {
      "filePath": "_authenticated/admin_/index.tsx",
      "parent": "/_authenticated/admin_"
    },
    "/_authenticated/events/": {
      "filePath": "_authenticated/events/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile/": {
      "filePath": "_authenticated/profile/index.tsx",
      "parent": "/_authenticated/profile"
    },
    "/_authenticated/admin_/api-keys/create": {
      "filePath": "_authenticated/admin_/api-keys/create.tsx",
      "parent": "/_authenticated/admin_"
    },
    "/_authenticated/admin_/event-parsing/$ruleId": {
      "filePath": "_authenticated/admin_/event-parsing/$ruleId.tsx",
      "parent": "/_authenticated/admin_"
    },
    "/_authenticated/admin_/event-parsing/create": {
      "filePath": "_authenticated/admin_/event-parsing/create.tsx",
      "parent": "/_authenticated/admin_"
    },
    "/_authenticated/admin_/users/$userId": {
      "filePath": "_authenticated/admin_/users/$userId.tsx",
      "parent": "/_authenticated/admin_",
      "children": [
        "/_authenticated/admin_/users/$userId/pending",
        "/_authenticated/admin_/users/$userId/sessions",
        "/_authenticated/admin_/users/$userId/summary",
        "/_authenticated/admin_/users/$userId/"
      ]
    },
    "/_authenticated/events/$eventId/check-in": {
      "filePath": "_authenticated/events/$eventId/check-in.tsx",
      "parent": "/_authenticated/events/$eventId"
    },
    "/_authenticated/events/$eventId/qr-code": {
      "filePath": "_authenticated/events/$eventId/qr-code.tsx",
      "parent": "/_authenticated/events/$eventId"
    },
    "/_authenticated/admin_/api-keys/": {
      "filePath": "_authenticated/admin_/api-keys/index.tsx",
      "parent": "/_authenticated/admin_"
    },
    "/_authenticated/admin_/event-parsing/": {
      "filePath": "_authenticated/admin_/event-parsing/index.tsx",
      "parent": "/_authenticated/admin_"
    },
    "/_authenticated/admin_/users/": {
      "filePath": "_authenticated/admin_/users/index.tsx",
      "parent": "/_authenticated/admin_"
    },
    "/_authenticated/events/$eventId/": {
      "filePath": "_authenticated/events/$eventId/index.tsx",
      "parent": "/_authenticated/events/$eventId"
    },
    "/_authenticated/admin_/users/$userId/pending": {
      "filePath": "_authenticated/admin_/users/$userId/pending.tsx",
      "parent": "/_authenticated/admin_/users/$userId"
    },
    "/_authenticated/admin_/users/$userId/sessions": {
      "filePath": "_authenticated/admin_/users/$userId/sessions.tsx",
      "parent": "/_authenticated/admin_/users/$userId"
    },
    "/_authenticated/admin_/users/$userId/summary": {
      "filePath": "_authenticated/admin_/users/$userId/summary.tsx",
      "parent": "/_authenticated/admin_/users/$userId"
    },
    "/_authenticated/admin_/users/$userId/": {
      "filePath": "_authenticated/admin_/users/$userId/index.tsx",
      "parent": "/_authenticated/admin_/users/$userId"
    }
  }
}
ROUTE_MANIFEST_END */
