/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ErrorImport } from './routes/error'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeaderboardImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedEventsImport } from './routes/_authenticated/events'
import { Route as AuthenticatedAdminImport } from './routes/_authenticated/admin_'
import { Route as AuthenticatedProfileIndexImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedAdminIndexImport } from './routes/_authenticated/admin_/index'
import { Route as AuthenticatedProfilePendingImport } from './routes/_authenticated/profile/pending'
import { Route as AuthenticatedEventsCreateImport } from './routes/_authenticated/events_/create'
import { Route as AuthenticatedEventsEventIdImport } from './routes/_authenticated/events_/$eventId'
import { Route as AuthenticatedEventsEventIdIndexImport } from './routes/_authenticated/events_/$eventId/index'
import { Route as AuthenticatedEventsEventIdQrCodeImport } from './routes/_authenticated/events_/$eventId/qr-code'
import { Route as AuthenticatedEventsEventIdCheckInImport } from './routes/_authenticated/events_/$eventId/check-in'
import { Route as AuthenticatedAdminUsersUserIdImport } from './routes/_authenticated/admin_/users.$userId'
import { Route as AuthenticatedAdminUsersUserIdIndexImport } from './routes/_authenticated/admin_/users.$userId/index'
import { Route as AuthenticatedAdminUsersUserIdPendingImport } from './routes/_authenticated/admin_/users.$userId/pending'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLeaderboardRoute = AuthenticatedLeaderboardImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedEventsRoute = AuthenticatedEventsImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAdminRoute = AuthenticatedAdminImport.update({
  id: '/admin_',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileIndexRoute = AuthenticatedProfileIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedProfileRoute,
} as any)

const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedProfilePendingRoute =
  AuthenticatedProfilePendingImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

const AuthenticatedEventsCreateRoute = AuthenticatedEventsCreateImport.update({
  id: '/events_/create',
  path: '/events/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedEventsEventIdRoute = AuthenticatedEventsEventIdImport.update(
  {
    id: '/events_/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedEventsEventIdIndexRoute =
  AuthenticatedEventsEventIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)

const AuthenticatedEventsEventIdQrCodeRoute =
  AuthenticatedEventsEventIdQrCodeImport.update({
    id: '/qr-code',
    path: '/qr-code',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)

const AuthenticatedEventsEventIdCheckInRoute =
  AuthenticatedEventsEventIdCheckInImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)

const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

const AuthenticatedAdminUsersUserIdIndexRoute =
  AuthenticatedAdminUsersUserIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)

const AuthenticatedAdminUsersUserIdPendingRoute =
  AuthenticatedAdminUsersUserIdPendingImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin_': {
      id: '/_authenticated/admin_'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/events_/$eventId': {
      id: '/_authenticated/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/events_/create': {
      id: '/_authenticated/events_/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof AuthenticatedEventsCreateImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile/pending': {
      id: '/_authenticated/profile/pending'
      path: '/pending'
      fullPath: '/profile/pending'
      preLoaderRoute: typeof AuthenticatedProfilePendingImport
      parentRoute: typeof AuthenticatedProfileImport
    }
    '/_authenticated/admin_/': {
      id: '/_authenticated/admin_/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexImport
      parentRoute: typeof AuthenticatedProfileImport
    }
    '/_authenticated/admin_/users/$userId': {
      id: '/_authenticated/admin_/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/events_/$eventId/check-in': {
      id: '/_authenticated/events_/$eventId/check-in'
      path: '/check-in'
      fullPath: '/events/$eventId/check-in'
      preLoaderRoute: typeof AuthenticatedEventsEventIdCheckInImport
      parentRoute: typeof AuthenticatedEventsEventIdImport
    }
    '/_authenticated/events_/$eventId/qr-code': {
      id: '/_authenticated/events_/$eventId/qr-code'
      path: '/qr-code'
      fullPath: '/events/$eventId/qr-code'
      preLoaderRoute: typeof AuthenticatedEventsEventIdQrCodeImport
      parentRoute: typeof AuthenticatedEventsEventIdImport
    }
    '/_authenticated/events_/$eventId/': {
      id: '/_authenticated/events_/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedEventsEventIdIndexImport
      parentRoute: typeof AuthenticatedEventsEventIdImport
    }
    '/_authenticated/admin_/users/$userId/pending': {
      id: '/_authenticated/admin_/users/$userId/pending'
      path: '/pending'
      fullPath: '/admin/users/$userId/pending'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdPendingImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdImport
    }
    '/_authenticated/admin_/users/$userId/': {
      id: '/_authenticated/admin_/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdIndexImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAdminUsersUserIdRouteChildren {
  AuthenticatedAdminUsersUserIdPendingRoute: typeof AuthenticatedAdminUsersUserIdPendingRoute
  AuthenticatedAdminUsersUserIdIndexRoute: typeof AuthenticatedAdminUsersUserIdIndexRoute
}

const AuthenticatedAdminUsersUserIdRouteChildren: AuthenticatedAdminUsersUserIdRouteChildren =
  {
    AuthenticatedAdminUsersUserIdPendingRoute:
      AuthenticatedAdminUsersUserIdPendingRoute,
    AuthenticatedAdminUsersUserIdIndexRoute:
      AuthenticatedAdminUsersUserIdIndexRoute,
  }

const AuthenticatedAdminUsersUserIdRouteWithChildren =
  AuthenticatedAdminUsersUserIdRoute._addFileChildren(
    AuthenticatedAdminUsersUserIdRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminUsersUserIdRoute:
    AuthenticatedAdminUsersUserIdRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfilePendingRoute: typeof AuthenticatedProfilePendingRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfilePendingRoute: AuthenticatedProfilePendingRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedEventsEventIdRouteChildren {
  AuthenticatedEventsEventIdCheckInRoute: typeof AuthenticatedEventsEventIdCheckInRoute
  AuthenticatedEventsEventIdQrCodeRoute: typeof AuthenticatedEventsEventIdQrCodeRoute
  AuthenticatedEventsEventIdIndexRoute: typeof AuthenticatedEventsEventIdIndexRoute
}

const AuthenticatedEventsEventIdRouteChildren: AuthenticatedEventsEventIdRouteChildren =
  {
    AuthenticatedEventsEventIdCheckInRoute:
      AuthenticatedEventsEventIdCheckInRoute,
    AuthenticatedEventsEventIdQrCodeRoute:
      AuthenticatedEventsEventIdQrCodeRoute,
    AuthenticatedEventsEventIdIndexRoute: AuthenticatedEventsEventIdIndexRoute,
  }

const AuthenticatedEventsEventIdRouteWithChildren =
  AuthenticatedEventsEventIdRoute._addFileChildren(
    AuthenticatedEventsEventIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRouteWithChildren
  AuthenticatedEventsCreateRoute: typeof AuthenticatedEventsCreateRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRouteWithChildren,
  AuthenticatedEventsCreateRoute: AuthenticatedEventsCreateRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/events': typeof AuthenticatedEventsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRouteWithChildren
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  '/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
  '/admin/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}

export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/events': typeof AuthenticatedEventsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdIndexRoute
  '/admin/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin_': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/events_/$eventId': typeof AuthenticatedEventsEventIdRouteWithChildren
  '/_authenticated/events_/create': typeof AuthenticatedEventsCreateRoute
  '/_authenticated/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/_authenticated/admin_/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/admin_/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  '/_authenticated/events_/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/_authenticated/events_/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/_authenticated/events_/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
  '/_authenticated/admin_/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/_authenticated/admin_/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/error'
    | '/login'
    | '/admin'
    | '/events'
    | '/leaderboard'
    | '/profile'
    | '/'
    | '/events/$eventId'
    | '/events/create'
    | '/profile/pending'
    | '/admin/'
    | '/profile/'
    | '/admin/users/$userId'
    | '/events/$eventId/check-in'
    | '/events/$eventId/qr-code'
    | '/events/$eventId/'
    | '/admin/users/$userId/pending'
    | '/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/login'
    | '/events'
    | '/leaderboard'
    | '/'
    | '/events/create'
    | '/profile/pending'
    | '/admin'
    | '/profile'
    | '/events/$eventId/check-in'
    | '/events/$eventId/qr-code'
    | '/events/$eventId'
    | '/admin/users/$userId/pending'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/error'
    | '/login'
    | '/_authenticated/admin_'
    | '/_authenticated/events'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/events_/$eventId'
    | '/_authenticated/events_/create'
    | '/_authenticated/profile/pending'
    | '/_authenticated/admin_/'
    | '/_authenticated/profile/'
    | '/_authenticated/admin_/users/$userId'
    | '/_authenticated/events_/$eventId/check-in'
    | '/_authenticated/events_/$eventId/qr-code'
    | '/_authenticated/events_/$eventId/'
    | '/_authenticated/admin_/users/$userId/pending'
    | '/_authenticated/admin_/users/$userId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/error",
        "/login"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/admin_",
        "/_authenticated/events",
        "/_authenticated/leaderboard",
        "/_authenticated/profile",
        "/_authenticated/",
        "/_authenticated/events_/$eventId",
        "/_authenticated/events_/create"
      ]
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/admin_": {
      "filePath": "_authenticated/admin_.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin_/",
        "/_authenticated/admin_/users/$userId"
      ]
    },
    "/_authenticated/events": {
      "filePath": "_authenticated/events.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/leaderboard": {
      "filePath": "_authenticated/leaderboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/profile/pending",
        "/_authenticated/profile/"
      ]
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/events_/$eventId": {
      "filePath": "_authenticated/events_/$eventId.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/events_/$eventId/check-in",
        "/_authenticated/events_/$eventId/qr-code",
        "/_authenticated/events_/$eventId/"
      ]
    },
    "/_authenticated/events_/create": {
      "filePath": "_authenticated/events_/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile/pending": {
      "filePath": "_authenticated/profile/pending.tsx",
      "parent": "/_authenticated/profile"
    },
    "/_authenticated/admin_/": {
      "filePath": "_authenticated/admin_/index.tsx",
      "parent": "/_authenticated/admin_"
    },
    "/_authenticated/profile/": {
      "filePath": "_authenticated/profile/index.tsx",
      "parent": "/_authenticated/profile"
    },
    "/_authenticated/admin_/users/$userId": {
      "filePath": "_authenticated/admin_/users.$userId.tsx",
      "parent": "/_authenticated/admin_",
      "children": [
        "/_authenticated/admin_/users/$userId/pending",
        "/_authenticated/admin_/users/$userId/"
      ]
    },
    "/_authenticated/events_/$eventId/check-in": {
      "filePath": "_authenticated/events_/$eventId/check-in.tsx",
      "parent": "/_authenticated/events_/$eventId"
    },
    "/_authenticated/events_/$eventId/qr-code": {
      "filePath": "_authenticated/events_/$eventId/qr-code.tsx",
      "parent": "/_authenticated/events_/$eventId"
    },
    "/_authenticated/events_/$eventId/": {
      "filePath": "_authenticated/events_/$eventId/index.tsx",
      "parent": "/_authenticated/events_/$eventId"
    },
    "/_authenticated/admin_/users/$userId/pending": {
      "filePath": "_authenticated/admin_/users.$userId/pending.tsx",
      "parent": "/_authenticated/admin_/users/$userId"
    },
    "/_authenticated/admin_/users/$userId/": {
      "filePath": "_authenticated/admin_/users.$userId/index.tsx",
      "parent": "/_authenticated/admin_/users/$userId"
    }
  }
}
ROUTE_MANIFEST_END */
