/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import type {
  FileRoutesByPath,
  CreateServerFileRoute,
} from '@tanstack/react-start/server'
import {
  createServerRoute,
  createServerFileRoute,
} from '@tanstack/react-start/server'

import { ServerRoute as ApiInteractionRouteImport } from './../../src/routes/api/interaction'
import { ServerRoute as ApiAuthDiscordRouteImport } from './../../src/routes/api/auth.discord'
import { ServerRoute as ApiSchedulerReminderTriggerRouteImport } from './../../src/routes/api/scheduler.reminder.trigger'
import { ServerRoute as ApiSchedulerCalendarTriggerRouteImport } from './../../src/routes/api/scheduler.calendar.trigger'
import { ServerRoute as ApiAuthDiscordCallbackRouteImport } from './../../src/routes/api/auth.discord.callback'

// Create/Update Routes

const rootRoute = createServerRoute()

const ApiInteractionRoute = ApiInteractionRouteImport.update({
  id: '/api/interaction',
  path: '/api/interaction',
  getParentRoute: () => rootRoute,
} as any)

const ApiAuthDiscordRoute = ApiAuthDiscordRouteImport.update({
  id: '/api/auth/discord',
  path: '/api/auth/discord',
  getParentRoute: () => rootRoute,
} as any)

const ApiSchedulerReminderTriggerRoute =
  ApiSchedulerReminderTriggerRouteImport.update({
    id: '/api/scheduler/reminder/trigger',
    path: '/api/scheduler/reminder/trigger',
    getParentRoute: () => rootRoute,
  } as any)

const ApiSchedulerCalendarTriggerRoute =
  ApiSchedulerCalendarTriggerRouteImport.update({
    id: '/api/scheduler/calendar/trigger',
    path: '/api/scheduler/calendar/trigger',
    getParentRoute: () => rootRoute,
  } as any)

const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthDiscordRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-start/server' {
  interface FileRoutesByPath {
    '/api/interaction': {
      id: '/api/interaction'
      path: '/api/interaction'
      fullPath: '/api/interaction'
      preLoaderRoute: typeof ApiInteractionRouteImport
      parentRoute: typeof rootRoute
    }
    '/api/auth/discord': {
      id: '/api/auth/discord'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord'
      preLoaderRoute: typeof ApiAuthDiscordRouteImport
      parentRoute: typeof rootRoute
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof ApiAuthDiscordRouteImport
    }
    '/api/scheduler/calendar/trigger': {
      id: '/api/scheduler/calendar/trigger'
      path: '/api/scheduler/calendar/trigger'
      fullPath: '/api/scheduler/calendar/trigger'
      preLoaderRoute: typeof ApiSchedulerCalendarTriggerRouteImport
      parentRoute: typeof rootRoute
    }
    '/api/scheduler/reminder/trigger': {
      id: '/api/scheduler/reminder/trigger'
      path: '/api/scheduler/reminder/trigger'
      fullPath: '/api/scheduler/reminder/trigger'
      preLoaderRoute: typeof ApiSchedulerReminderTriggerRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './../../src/routes/api/interaction' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/interaction']['parentRoute'],
    FileRoutesByPath['/api/interaction']['id'],
    FileRoutesByPath['/api/interaction']['path'],
    FileRoutesByPath['/api/interaction']['fullPath'],
    unknown
  >
}
declare module './../../src/routes/api/auth.discord' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/auth/discord']['parentRoute'],
    FileRoutesByPath['/api/auth/discord']['id'],
    FileRoutesByPath['/api/auth/discord']['path'],
    FileRoutesByPath['/api/auth/discord']['fullPath'],
    ApiAuthDiscordRouteChildren
  >
}
declare module './../../src/routes/api/auth.discord.callback' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/auth/discord/callback']['parentRoute'],
    FileRoutesByPath['/api/auth/discord/callback']['id'],
    FileRoutesByPath['/api/auth/discord/callback']['path'],
    FileRoutesByPath['/api/auth/discord/callback']['fullPath'],
    unknown
  >
}
declare module './../../src/routes/api/scheduler.calendar.trigger' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/scheduler/calendar/trigger']['parentRoute'],
    FileRoutesByPath['/api/scheduler/calendar/trigger']['id'],
    FileRoutesByPath['/api/scheduler/calendar/trigger']['path'],
    FileRoutesByPath['/api/scheduler/calendar/trigger']['fullPath'],
    unknown
  >
}
declare module './../../src/routes/api/scheduler.reminder.trigger' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/scheduler/reminder/trigger']['parentRoute'],
    FileRoutesByPath['/api/scheduler/reminder/trigger']['id'],
    FileRoutesByPath['/api/scheduler/reminder/trigger']['path'],
    FileRoutesByPath['/api/scheduler/reminder/trigger']['fullPath'],
    unknown
  >
}

// Create and export the route tree

interface ApiAuthDiscordRouteChildren {
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
}

const ApiAuthDiscordRouteChildren: ApiAuthDiscordRouteChildren = {
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
}

const ApiAuthDiscordRouteWithChildren = ApiAuthDiscordRoute._addFileChildren(
  ApiAuthDiscordRouteChildren,
)

export interface FileRoutesByFullPath {
  '/api/interaction': typeof ApiInteractionRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/scheduler/calendar/trigger': typeof ApiSchedulerCalendarTriggerRoute
  '/api/scheduler/reminder/trigger': typeof ApiSchedulerReminderTriggerRoute
}

export interface FileRoutesByTo {
  '/api/interaction': typeof ApiInteractionRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/scheduler/calendar/trigger': typeof ApiSchedulerCalendarTriggerRoute
  '/api/scheduler/reminder/trigger': typeof ApiSchedulerReminderTriggerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/api/interaction': typeof ApiInteractionRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/scheduler/calendar/trigger': typeof ApiSchedulerCalendarTriggerRoute
  '/api/scheduler/reminder/trigger': typeof ApiSchedulerReminderTriggerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/interaction'
    | '/api/auth/discord'
    | '/api/auth/discord/callback'
    | '/api/scheduler/calendar/trigger'
    | '/api/scheduler/reminder/trigger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/interaction'
    | '/api/auth/discord'
    | '/api/auth/discord/callback'
    | '/api/scheduler/calendar/trigger'
    | '/api/scheduler/reminder/trigger'
  id:
    | '__root__'
    | '/api/interaction'
    | '/api/auth/discord'
    | '/api/auth/discord/callback'
    | '/api/scheduler/calendar/trigger'
    | '/api/scheduler/reminder/trigger'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ApiInteractionRoute: typeof ApiInteractionRoute
  ApiAuthDiscordRoute: typeof ApiAuthDiscordRouteWithChildren
  ApiSchedulerCalendarTriggerRoute: typeof ApiSchedulerCalendarTriggerRoute
  ApiSchedulerReminderTriggerRoute: typeof ApiSchedulerReminderTriggerRoute
}

const rootRouteChildren: RootRouteChildren = {
  ApiInteractionRoute: ApiInteractionRoute,
  ApiAuthDiscordRoute: ApiAuthDiscordRouteWithChildren,
  ApiSchedulerCalendarTriggerRoute: ApiSchedulerCalendarTriggerRoute,
  ApiSchedulerReminderTriggerRoute: ApiSchedulerReminderTriggerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/api/interaction",
        "/api/auth/discord",
        "/api/scheduler/calendar/trigger",
        "/api/scheduler/reminder/trigger"
      ]
    },
    "/api/interaction": {
      "filePath": "api/interaction.ts"
    },
    "/api/auth/discord": {
      "filePath": "api/auth.discord.ts",
      "children": [
        "/api/auth/discord/callback"
      ]
    },
    "/api/auth/discord/callback": {
      "filePath": "api/auth.discord.callback.ts",
      "parent": "/api/auth/discord"
    },
    "/api/scheduler/calendar/trigger": {
      "filePath": "api/scheduler.calendar.trigger.ts"
    },
    "/api/scheduler/reminder/trigger": {
      "filePath": "api/scheduler.reminder.trigger.ts"
    }
  }
}
ROUTE_MANIFEST_END */
