/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiInteractionRouteImport } from './routes/api/interaction'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin_'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin_/index'
import { Route as ApiAuthDiscordRouteImport } from './routes/api/auth.discord'
import { Route as AuthenticatedProfileSessionsRouteImport } from './routes/_authenticated/profile/sessions'
import { Route as AuthenticatedProfilePendingRouteImport } from './routes/_authenticated/profile/pending'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events/$eventId'
import { Route as AuthenticatedEventsEventIdIndexRouteImport } from './routes/_authenticated/events/$eventId/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin_/users/index'
import { Route as AuthenticatedAdminEventParsingIndexRouteImport } from './routes/_authenticated/admin_/event-parsing/index'
import { Route as ApiSchedulerCalendarTriggerRouteImport } from './routes/api/scheduler.calendar.trigger'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth.discord.callback'
import { Route as AuthenticatedEventsEventIdQrCodeRouteImport } from './routes/_authenticated/events/$eventId/qr-code'
import { Route as AuthenticatedEventsEventIdCheckInRouteImport } from './routes/_authenticated/events/$eventId/check-in'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin_/users/$userId'
import { Route as AuthenticatedAdminEventParsingCreateRouteImport } from './routes/_authenticated/admin_/event-parsing/create'
import { Route as AuthenticatedAdminEventParsingRuleIdRouteImport } from './routes/_authenticated/admin_/event-parsing/$ruleId'
import { Route as AuthenticatedAdminUsersUserIdIndexRouteImport } from './routes/_authenticated/admin_/users/$userId/index'
import { Route as AuthenticatedAdminUsersUserIdSessionsRouteImport } from './routes/_authenticated/admin_/users/$userId/sessions'
import { Route as AuthenticatedAdminUsersUserIdPendingRouteImport } from './routes/_authenticated/admin_/users/$userId/pending'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiInteractionRoute = ApiInteractionRouteImport.update({
  id: '/api/interaction',
  path: '/api/interaction',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin_',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiAuthDiscordRoute = ApiAuthDiscordRouteImport.update({
  id: '/api/auth/discord',
  path: '/api/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileSessionsRoute =
  AuthenticatedProfileSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfilePendingRoute =
  AuthenticatedProfilePendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsEventIdIndexRoute =
  AuthenticatedEventsEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventParsingIndexRoute =
  AuthenticatedAdminEventParsingIndexRouteImport.update({
    id: '/event-parsing/',
    path: '/event-parsing/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiSchedulerCalendarTriggerRoute =
  ApiSchedulerCalendarTriggerRouteImport.update({
    id: '/api/scheduler/calendar/trigger',
    path: '/api/scheduler/calendar/trigger',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthDiscordRoute,
} as any)
const AuthenticatedEventsEventIdQrCodeRoute =
  AuthenticatedEventsEventIdQrCodeRouteImport.update({
    id: '/qr-code',
    path: '/qr-code',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)
const AuthenticatedEventsEventIdCheckInRoute =
  AuthenticatedEventsEventIdCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventParsingCreateRoute =
  AuthenticatedAdminEventParsingCreateRouteImport.update({
    id: '/event-parsing/create',
    path: '/event-parsing/create',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventParsingRuleIdRoute =
  AuthenticatedAdminEventParsingRuleIdRouteImport.update({
    id: '/event-parsing/$ruleId',
    path: '/event-parsing/$ruleId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersUserIdIndexRoute =
  AuthenticatedAdminUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)
const AuthenticatedAdminUsersUserIdSessionsRoute =
  AuthenticatedAdminUsersUserIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)
const AuthenticatedAdminUsersUserIdPendingRoute =
  AuthenticatedAdminUsersUserIdPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/api/interaction': typeof ApiInteractionRoute
  '/': typeof AuthenticatedIndexRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRouteWithChildren
  '/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/profile/sessions': typeof AuthenticatedProfileSessionsRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/admin/event-parsing/$ruleId': typeof AuthenticatedAdminEventParsingRuleIdRoute
  '/admin/event-parsing/create': typeof AuthenticatedAdminEventParsingCreateRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  '/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/scheduler/calendar/trigger': typeof ApiSchedulerCalendarTriggerRoute
  '/admin/event-parsing': typeof AuthenticatedAdminEventParsingIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
  '/admin/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/admin/users/$userId/sessions': typeof AuthenticatedAdminUsersUserIdSessionsRoute
  '/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/api/interaction': typeof ApiInteractionRoute
  '/': typeof AuthenticatedIndexRoute
  '/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/profile/sessions': typeof AuthenticatedProfileSessionsRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/admin/event-parsing/$ruleId': typeof AuthenticatedAdminEventParsingRuleIdRoute
  '/admin/event-parsing/create': typeof AuthenticatedAdminEventParsingCreateRoute
  '/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/scheduler/calendar/trigger': typeof ApiSchedulerCalendarTriggerRoute
  '/admin/event-parsing': typeof AuthenticatedAdminEventParsingIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdIndexRoute
  '/admin/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/admin/users/$userId/sessions': typeof AuthenticatedAdminUsersUserIdSessionsRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin_': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/api/interaction': typeof ApiInteractionRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRouteWithChildren
  '/_authenticated/profile/pending': typeof AuthenticatedProfilePendingRoute
  '/_authenticated/profile/sessions': typeof AuthenticatedProfileSessionsRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/_authenticated/admin_/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/admin_/event-parsing/$ruleId': typeof AuthenticatedAdminEventParsingRuleIdRoute
  '/_authenticated/admin_/event-parsing/create': typeof AuthenticatedAdminEventParsingCreateRoute
  '/_authenticated/admin_/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  '/_authenticated/events/$eventId/check-in': typeof AuthenticatedEventsEventIdCheckInRoute
  '/_authenticated/events/$eventId/qr-code': typeof AuthenticatedEventsEventIdQrCodeRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/scheduler/calendar/trigger': typeof ApiSchedulerCalendarTriggerRoute
  '/_authenticated/admin_/event-parsing/': typeof AuthenticatedAdminEventParsingIndexRoute
  '/_authenticated/admin_/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
  '/_authenticated/admin_/users/$userId/pending': typeof AuthenticatedAdminUsersUserIdPendingRoute
  '/_authenticated/admin_/users/$userId/sessions': typeof AuthenticatedAdminUsersUserIdSessionsRoute
  '/_authenticated/admin_/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/error'
    | '/login'
    | '/admin'
    | '/leaderboard'
    | '/profile'
    | '/api/interaction'
    | '/'
    | '/events/$eventId'
    | '/profile/pending'
    | '/profile/sessions'
    | '/api/auth/discord'
    | '/admin/'
    | '/profile/'
    | '/admin/event-parsing/$ruleId'
    | '/admin/event-parsing/create'
    | '/admin/users/$userId'
    | '/events/$eventId/check-in'
    | '/events/$eventId/qr-code'
    | '/api/auth/discord/callback'
    | '/api/scheduler/calendar/trigger'
    | '/admin/event-parsing'
    | '/admin/users'
    | '/events/$eventId/'
    | '/admin/users/$userId/pending'
    | '/admin/users/$userId/sessions'
    | '/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/login'
    | '/leaderboard'
    | '/api/interaction'
    | '/'
    | '/profile/pending'
    | '/profile/sessions'
    | '/api/auth/discord'
    | '/admin'
    | '/profile'
    | '/admin/event-parsing/$ruleId'
    | '/admin/event-parsing/create'
    | '/events/$eventId/check-in'
    | '/events/$eventId/qr-code'
    | '/api/auth/discord/callback'
    | '/api/scheduler/calendar/trigger'
    | '/admin/event-parsing'
    | '/admin/users'
    | '/events/$eventId'
    | '/admin/users/$userId/pending'
    | '/admin/users/$userId/sessions'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/error'
    | '/login'
    | '/_authenticated/admin_'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/api/interaction'
    | '/_authenticated/'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/profile/pending'
    | '/_authenticated/profile/sessions'
    | '/api/auth/discord'
    | '/_authenticated/admin_/'
    | '/_authenticated/profile/'
    | '/_authenticated/admin_/event-parsing/$ruleId'
    | '/_authenticated/admin_/event-parsing/create'
    | '/_authenticated/admin_/users/$userId'
    | '/_authenticated/events/$eventId/check-in'
    | '/_authenticated/events/$eventId/qr-code'
    | '/api/auth/discord/callback'
    | '/api/scheduler/calendar/trigger'
    | '/_authenticated/admin_/event-parsing/'
    | '/_authenticated/admin_/users/'
    | '/_authenticated/events/$eventId/'
    | '/_authenticated/admin_/users/$userId/pending'
    | '/_authenticated/admin_/users/$userId/sessions'
    | '/_authenticated/admin_/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  ApiInteractionRoute: typeof ApiInteractionRoute
  ApiAuthDiscordRoute: typeof ApiAuthDiscordRouteWithChildren
  ApiSchedulerCalendarTriggerRoute: typeof ApiSchedulerCalendarTriggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/interaction': {
      id: '/api/interaction'
      path: '/api/interaction'
      fullPath: '/api/interaction'
      preLoaderRoute: typeof ApiInteractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_': {
      id: '/_authenticated/admin_'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/admin_/': {
      id: '/_authenticated/admin_/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/auth/discord': {
      id: '/api/auth/discord'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord'
      preLoaderRoute: typeof ApiAuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/sessions': {
      id: '/_authenticated/profile/sessions'
      path: '/sessions'
      fullPath: '/profile/sessions'
      preLoaderRoute: typeof AuthenticatedProfileSessionsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/pending': {
      id: '/_authenticated/profile/pending'
      path: '/pending'
      fullPath: '/profile/pending'
      preLoaderRoute: typeof AuthenticatedProfilePendingRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$eventId/': {
      id: '/_authenticated/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRoute
    }
    '/_authenticated/admin_/users/': {
      id: '/_authenticated/admin_/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin_/event-parsing/': {
      id: '/_authenticated/admin_/event-parsing/'
      path: '/event-parsing'
      fullPath: '/admin/event-parsing'
      preLoaderRoute: typeof AuthenticatedAdminEventParsingIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/scheduler/calendar/trigger': {
      id: '/api/scheduler/calendar/trigger'
      path: '/api/scheduler/calendar/trigger'
      fullPath: '/api/scheduler/calendar/trigger'
      preLoaderRoute: typeof ApiSchedulerCalendarTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof ApiAuthDiscordRoute
    }
    '/_authenticated/events/$eventId/qr-code': {
      id: '/_authenticated/events/$eventId/qr-code'
      path: '/qr-code'
      fullPath: '/events/$eventId/qr-code'
      preLoaderRoute: typeof AuthenticatedEventsEventIdQrCodeRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRoute
    }
    '/_authenticated/events/$eventId/check-in': {
      id: '/_authenticated/events/$eventId/check-in'
      path: '/check-in'
      fullPath: '/events/$eventId/check-in'
      preLoaderRoute: typeof AuthenticatedEventsEventIdCheckInRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRoute
    }
    '/_authenticated/admin_/users/$userId': {
      id: '/_authenticated/admin_/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin_/event-parsing/create': {
      id: '/_authenticated/admin_/event-parsing/create'
      path: '/event-parsing/create'
      fullPath: '/admin/event-parsing/create'
      preLoaderRoute: typeof AuthenticatedAdminEventParsingCreateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin_/event-parsing/$ruleId': {
      id: '/_authenticated/admin_/event-parsing/$ruleId'
      path: '/event-parsing/$ruleId'
      fullPath: '/admin/event-parsing/$ruleId'
      preLoaderRoute: typeof AuthenticatedAdminEventParsingRuleIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin_/users/$userId/': {
      id: '/_authenticated/admin_/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRoute
    }
    '/_authenticated/admin_/users/$userId/sessions': {
      id: '/_authenticated/admin_/users/$userId/sessions'
      path: '/sessions'
      fullPath: '/admin/users/$userId/sessions'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRoute
    }
    '/_authenticated/admin_/users/$userId/pending': {
      id: '/_authenticated/admin_/users/$userId/pending'
      path: '/pending'
      fullPath: '/admin/users/$userId/pending'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdPendingRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRoute
    }
  }
}

interface AuthenticatedAdminUsersUserIdRouteChildren {
  AuthenticatedAdminUsersUserIdPendingRoute: typeof AuthenticatedAdminUsersUserIdPendingRoute
  AuthenticatedAdminUsersUserIdSessionsRoute: typeof AuthenticatedAdminUsersUserIdSessionsRoute
  AuthenticatedAdminUsersUserIdIndexRoute: typeof AuthenticatedAdminUsersUserIdIndexRoute
}

const AuthenticatedAdminUsersUserIdRouteChildren: AuthenticatedAdminUsersUserIdRouteChildren =
  {
    AuthenticatedAdminUsersUserIdPendingRoute:
      AuthenticatedAdminUsersUserIdPendingRoute,
    AuthenticatedAdminUsersUserIdSessionsRoute:
      AuthenticatedAdminUsersUserIdSessionsRoute,
    AuthenticatedAdminUsersUserIdIndexRoute:
      AuthenticatedAdminUsersUserIdIndexRoute,
  }

const AuthenticatedAdminUsersUserIdRouteWithChildren =
  AuthenticatedAdminUsersUserIdRoute._addFileChildren(
    AuthenticatedAdminUsersUserIdRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventParsingRuleIdRoute: typeof AuthenticatedAdminEventParsingRuleIdRoute
  AuthenticatedAdminEventParsingCreateRoute: typeof AuthenticatedAdminEventParsingCreateRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  AuthenticatedAdminEventParsingIndexRoute: typeof AuthenticatedAdminEventParsingIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEventParsingRuleIdRoute:
    AuthenticatedAdminEventParsingRuleIdRoute,
  AuthenticatedAdminEventParsingCreateRoute:
    AuthenticatedAdminEventParsingCreateRoute,
  AuthenticatedAdminUsersUserIdRoute:
    AuthenticatedAdminUsersUserIdRouteWithChildren,
  AuthenticatedAdminEventParsingIndexRoute:
    AuthenticatedAdminEventParsingIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfilePendingRoute: typeof AuthenticatedProfilePendingRoute
  AuthenticatedProfileSessionsRoute: typeof AuthenticatedProfileSessionsRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfilePendingRoute: AuthenticatedProfilePendingRoute,
  AuthenticatedProfileSessionsRoute: AuthenticatedProfileSessionsRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedEventsEventIdRouteChildren {
  AuthenticatedEventsEventIdCheckInRoute: typeof AuthenticatedEventsEventIdCheckInRoute
  AuthenticatedEventsEventIdQrCodeRoute: typeof AuthenticatedEventsEventIdQrCodeRoute
  AuthenticatedEventsEventIdIndexRoute: typeof AuthenticatedEventsEventIdIndexRoute
}

const AuthenticatedEventsEventIdRouteChildren: AuthenticatedEventsEventIdRouteChildren =
  {
    AuthenticatedEventsEventIdCheckInRoute:
      AuthenticatedEventsEventIdCheckInRoute,
    AuthenticatedEventsEventIdQrCodeRoute:
      AuthenticatedEventsEventIdQrCodeRoute,
    AuthenticatedEventsEventIdIndexRoute: AuthenticatedEventsEventIdIndexRoute,
  }

const AuthenticatedEventsEventIdRouteWithChildren =
  AuthenticatedEventsEventIdRoute._addFileChildren(
    AuthenticatedEventsEventIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiAuthDiscordRouteChildren {
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
}

const ApiAuthDiscordRouteChildren: ApiAuthDiscordRouteChildren = {
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
}

const ApiAuthDiscordRouteWithChildren = ApiAuthDiscordRoute._addFileChildren(
  ApiAuthDiscordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  ApiInteractionRoute: ApiInteractionRoute,
  ApiAuthDiscordRoute: ApiAuthDiscordRouteWithChildren,
  ApiSchedulerCalendarTriggerRoute: ApiSchedulerCalendarTriggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
